---

- tags:
    - setup-all
    - setup-matrix-ldap-registration-proxy
    - install-all
    - install-matrix-ldap-registration-proxy
  block:
    - when: matrix_ldap_registration_proxy_enabled | bool
      ansible.builtin.include_tasks: "{{ role_path }}/tasks/validate_config.yml"

    - when: matrix_ldap_registration_proxy_enabled | bool
      ansible.builtin.include_tasks: "{{ role_path }}/tasks/setup_install.yml"

- tags:
    - setup-all
    - setup-matrix-ldap-registration-proxy
  block:
    - when: not matrix_ldap_registration_proxy_enabled | bool
      ansible.builtin.include_tasks: "{{ role_path }}/tasks/setup_uninstall.yml"
