---

- name: (Deprecation) Catch and report renamed Coturn settings
  ansible.builtin.fail:
    msg: >-
      Your configuration contains a variable, which now has a different name.
      Please change your configuration to rename the variable (`{{ item.old }}` -> `{{ item.new }}`).
  when: "item.old in vars"
  with_items:
    - {'old': 'matrix_coturn_docker_network', 'new': 'matrix_coturn_container_network'}

- name: Fail if required Coturn settings not defined
  ansible.builtin.fail:
    msg: >-
      You need to define a required configuration setting (`{{ item }}`) for using Coturn.
  when: "vars[item] == ''"
  with_items:
    - "matrix_coturn_turn_static_auth_secret"
